name: release

on:
  workflow_dispatch:

jobs:
  release:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: deps
        run: python -m pip install -U cibuildwheel build pip wheel setuptools

      - name: sdist
        run: python -m build --sdist --outdir package

      - name: wheels
        run: python -m cibuildwheel --output-dir package
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.10"
          CIBW_ARCHS: native
          CIBW_SKIP: pp*

      - uses: actions/upload-artifact@v4
        with:
          name: cudart-1.0.1
          path: package/*
